behaviors:
  TankyBrain:
    trainer_type: ppo
    hyperparameters:
      batch_size: 4096
      buffer_size: 80000 # ~x20 multiplier
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    self_play:
      save_steps: 20000
      team_change: 100000
      swap_steps: 10000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
    max_steps: 1500000 # ~1.5M steps/hr for 4 headless environments
    time_horizon: 256
    summary_freq: 20000
    checkpoint_interval: 100000
    keep_checkpoints: 50

environment_parameters:
  stages:
    curriculum:
      - name: level_1a # 7m spawns, front-facing (30 degree arc)
        completion_criteria:
          measure: reward
          behavior: TankyBrain
          signal_smoothing: true
          min_lesson_length: 150
          threshold: 1.1
        value: 0.0
      - name: level_1b # 12m spawns, front-facing (60 degree arc)
        completion_criteria:
          measure: reward
          behavior: TankyBrain
          signal_smoothing: true
          min_lesson_length: 150
          threshold: 1.2
        value: 1.0
      - name: level_2 # 20m spawns, single obstacle, front-facing (60 degree arc)
        completion_criteria:
          measure: reward
          behavior: TankyBrain
          signal_smoothing: true
          min_lesson_length: 150
          threshold: 1.3
        value: 2.0
      - name: level_3 # 25m spawns, multiple obstacles, multiple spawns, front-facing (90 degree arc)
        completion_criteria:
          measure: reward
          behavior: TankyBrain
          signal_smoothing: true
          min_lesson_length: 150
          threshold: 1.4
        value: 3.0
      - name: main_battle # move to the main battlefield. fights on!
        value: 4.0
